DROP TABLE IF EXISTS CIDR_BIT_BLOCK;

CREATE TABLE CIDR_BIT_BLOCK (
  ID INT PRIMARY KEY,
  ENCODED_BITS VARCHAR
);

DROP TABLE IF EXISTS CIDR_DEF;
CREATE TABLE CIDR_DEF (
  CIDR VARCHAR PRIMARY KEY
);